### ISSUE TITLE
DOES NOT WORK in 1.21.3

### ISSUE THREAD

**Issue by Darkmager** [bivashy/NanoLimboPlugin#20] opened 2024-12-09 12:44 UTC
using on Velocity 3.4.0-SNAPSHOT, it says client version unsupported on 1.21.3 users

**Comment by bivashy** [comment] 2024-12-10 07:44
Duplicate of https://github.com/Nan1t/NanoLimbo/issues/97

**Closed as not planned by bivashy** 2024-12-10 07:44 UTC
